version: "3.7"
services:
  nextcloud-db:
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - "3306:3306" # 加入這行，將主機 3306 映射到容器 3306
    environment:
      - MYSQL_ROOT_PASSWORD=upspi
      - MYSQL_PASSWORD=upspi
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - nextclouddb:/var/lib/mysql
    networks:
      - n8n-network

  redis:
    image: redis:7
    restart: always
    # volumes:
    #   - ./redis:/data
    networks:
      - n8n-network

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8085:80
    depends_on:
      - redis
      - nextcloud-db
    volumes:
      - nextcloud:/var/www/html
      # below mapping is for using External Storage (local) to mount samba shared folder into Nextcloud. Change as needed.
      # - /home/upspi/Desktop/share/nextcloud_share:/mnt/samba
      - /mnt/d/tmp/for_nextcloud:/var/local
    environment:
      - MYSQL_PASSWORD=upspi
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password123
    networks:
      - n8n-network

volumes:
  nextcloud:
  nextclouddb:

networks:
  n8n-network:
    external: true # 這代表網路已經透過 'docker network create n8n-network' 建立過了
